version: '3.8'

x-airflow-common: &airflow-common
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__WARN_DEPLOYMENT_EXPOSURE: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'your_airflow_webserver_sec_key'
    _PIP_ADDITIONAL_REQUIREMENTS: "clickhouse-driver psycopg2-binary minio"

services:
  # Task1.3: Authenticaton service (BFF - backend for frontend)  
  auth-service:
    container_name: bionicpro-auth-service
    hostname: auth-service
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak_db:
    container_name: bionicpro-postgres
    hostname: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 5s
      timeout: 3s
      retries: 10
  keycloak:
    container_name: bionicpro-keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HEALTH_ENABLED: true
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          exec 3<>/dev/tcp/127.0.0.1/9000;
          echo -e "GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n" >&3;
          if cat <&3 | grep -q "\"status\": \"UP\""; then
            exit 0
          else
            exit 1
          fi
      interval: 30s
      timeout: 10s
      retries: 3  
    depends_on:
      keycloak_db:
        condition: service_healthy
  frontend:
    container_name: bionicpro-frontend
    hostname: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
  
  # Task 1.4: LDAP integration
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --copy-service
    volumes:
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    environment:
      - LDAP_ORGANISATION=example-com
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"

# Task 2.1: DAG pipeline with Airflow
  crm_db:
    image: postgres:14
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=4
      -c max_wal_senders=4
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password
    volumes:
      - ./crm-db:/docker-entrypoint-initdb.d
      - ./postgres-crm-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 5s
      timeout: 3s
      retries: 10

  olap_db:
    image: clickhouse/clickhouse-server:24.8
    networks:
      default:
        aliases:
          - olapdb
    ports:
      - "8123:8123"
      - "9431:9000"
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
      - ./olap-db:/docker-entrypoint-initdb.d
      - ./olap-db:/var/lib/clickhouse/user_files
      - ./olap-db/users.xml:/etc/clickhouse-server/users.d/users.xml
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 1s
      timeout: 3s
      retries: 30

  airflow_db:
    image: postgres:14
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - ./postgres-airflow-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      timeout: 3s
      retries: 10

  airflow-init:
    <<: *airflow-common
    image: apache/airflow:2.8.1
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init &&
        airflow users create \
          --username admin --password admin \
          --firstname Admin --lastname User \
          --role Admin --email admin@example.com
    depends_on:
      airflow_db:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common  
    image: apache/airflow:2.8.1
    command: webserver
    ports:
      - "8085:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common  
    image: apache/airflow:2.8.1
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - airflow-init
