proxy_cache_path /var/cache/nginx/s3
    levels=1:2
    keys_zone=s3_cache:10m
    max_size=1g
    inactive=24h
    use_temp_path=off;

server {
    listen 80;
    server_name _;

    # Проксирование к MinIO с кэшированием (эмуляция CDN)
    location /cdn/reports/ {
        rewrite ^/cdn/(.*)$ /$1 break;

        proxy_pass http://minio:9000;
        proxy_cache s3_cache;
        proxy_cache_valid 200 24h;
        proxy_cache_valid 404 1m; 
        proxy_cache_key $uri;
        add_header X-Cache-Status $upstream_cache_status always;
        add_header X-Cache-Key $uri always;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
        proxy_set_header Authorization "";
        proxy_set_header Host $host;
    }

    location /nginx-health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}